#!/usr/bin/env python3
"""Generate EDBT paper macros, tables, and figures from governed CSV assets.

The three CSV files in ``source_data/generated`` are the only paper-facing
numeric inputs.  This script performs formatting and visualization only; it
does not recompute estimands or claim states.
"""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np


PAPER = Path(__file__).resolve().parents[1]
ROOT = PAPER.parents[1]
SOURCE = PAPER / "source_data/generated"
GENERATED = PAPER / "generated"
FIGURES = PAPER / "figures/generated"
FULL_B1 = ROOT / "results/edbt_t0_b_full_b1_analysis"

# Flat colors sampled from the author-provided ML visualization palette.
PALETTE = {
    "p3": "#3F2B96",
    "p2": "#A8C0FF",
    "simple": "#FE9696",
    "boundary": "#E6B94E",
    "structured": "#B6D7A8",
    "lavender": "#DBD4EB",
    "cyan": "#69D4F4",
    "ink": "#4A4655",
    "neutral": "#8A8793",
    "grid": "#E8E6EC",
}

mpl.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": 7,
        "axes.labelsize": 7,
        "axes.titlesize": 8,
        "xtick.labelsize": 6.5,
        "ytick.labelsize": 6.5,
        "legend.fontsize": 6.5,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.linewidth": 0.7,
        "legend.frameon": False,
        "svg.fonttype": "none",
        "svg.hashsalt": "leakbench-edbt-eab-v1",
        "pdf.fonttype": 42,
    }
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_rows(name: str) -> list[dict[str, str]]:
    with (SOURCE / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def read_path(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def parse_interval(value: str) -> tuple[float, float, float]:
    point, interval = value.split(" [", 1)
    low, high = interval.rstrip("]").split(", ", 1)
    return float(point), float(low), float(high)


def tex_effect(value: str) -> str:
    point, low, high = parse_interval(value)
    return (
        rf"\shortstack{{{point:+.3f}\\[-1pt]"
        rf"{{\scriptsize [{low:+.3f},{high:+.3f}]}}}}"
    )


def number(value: str) -> float:
    return float(value)


def fmt(value: str | float, digits: int = 3, signed: bool = False) -> str:
    numeric = float(value)
    return f"{numeric:+.{digits}f}" if signed else f"{numeric:.{digits}f}"


def tex_escape(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "_": r"\_",
        "#": r"\#",
    }
    return "".join(replacements.get(char, char) for char in value)


def write_macros(main: list[dict[str, str]], gov: list[dict[str, str]], natural: list[dict[str, str]], policies: list[dict[str, str]]) -> Path:
    contrast = next(row for row in main if row["result_id"] == "C1")
    budget = {row["scope"]: row for row in gov if row["row_type"] == "budget"}
    category = {row["scope"]: row for row in gov if row["row_type"] == "category_at_20pct"}
    p3 = next(row for row in policies if row["policy"] == "P3")
    p3_sdr = parse_interval(p3["delta_legacy_sdr"])
    p3_direction = parse_interval(p3["delta_directional_repair"])
    p3_recall = parse_interval(p3["delta_full_group_recall"])
    p3_over = parse_interval(p3["delta_overcorrection"])
    lines = [
        "% Generated by source_data/generate_paper_artifacts.py; do not edit.",
        rf"\newcommand{{\CoreCellCount}}{{27,500}}",
        rf"\newcommand{{\GovernanceCellCount}}{{55,000}}",
        rf"\newcommand{{\GovernanceKeyCount}}{{5,500}}",
        rf"\newcommand{{\FullBOneCellCount}}{{803,000}}",
        rf"\newcommand{{\FullBOneGovernedCount}}{{792,000}}",
        rf"\newcommand{{\CoreContrast}}{{{fmt(contrast['estimate'])}}}",
        rf"\newcommand{{\CoreContrastLow}}{{{fmt(contrast['ci_low'])}}}",
        rf"\newcommand{{\CoreContrastHigh}}{{{fmt(contrast['ci_high'])}}}",
        rf"\newcommand{{\CoreContrastP}}{{{float(contrast['holm_p']):.2e}}}",
        rf"\newcommand{{\GovTwentyDiff}}{{{fmt(budget['20% budget']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyLow}}{{{fmt(budget['20% budget']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyHigh}}{{{fmt(budget['20% budget']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyProb}}{{{100 * number(budget['20% budget']['p3_better_probability']):.1f}\%}}",
        rf"\newcommand{{\GovOneDiff}}{{{fmt(budget['1% budget']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovOneRecall}}{{{100 * number(budget['1% budget']['p3_recall']):.1f}\%}}",
        rf"\newcommand{{\GovOneRetention}}{{{100 * number(budget['1% budget']['p3_legitimate_retention']):.1f}\%}}",
        rf"\newcommand{{\GovSimpleDiff}}{{{fmt(category['simple']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleLow}}{{{fmt(category['simple']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleHigh}}{{{fmt(category['simple']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryDiff}}{{{fmt(category['boundary']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryLow}}{{{fmt(category['boundary']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryHigh}}{{{fmt(category['boundary']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredDiff}}{{{fmt(category['structured']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredLow}}{{{fmt(category['structured']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredHigh}}{{{fmt(category['structured']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\NaturalCaseCount}}{{{len(natural)}}}",
        rf"\newcommand{{\NaturalMeanHarm}}{{{fmt(np.mean([number(row['mean_paired_harm']) for row in natural]))}}}",
        rf"\newcommand{{\PrimaryPolicyStatus}}{{{p3['claim_status']}}}",
        rf"\newcommand{{\PrimarySdr}}{{{p3_sdr[0]:+.3f}}}",
        rf"\newcommand{{\PrimarySdrLow}}{{{p3_sdr[1]:+.3f}}}",
        rf"\newcommand{{\PrimarySdrHigh}}{{{p3_sdr[2]:+.3f}}}",
        rf"\newcommand{{\PrimaryDirection}}{{{p3_direction[0]:+.3f}}}",
        rf"\newcommand{{\PrimaryDirectionLow}}{{{p3_direction[1]:+.3f}}}",
        rf"\newcommand{{\PrimaryDirectionHigh}}{{{p3_direction[2]:+.3f}}}",
        rf"\newcommand{{\PrimaryGroupRecall}}{{{p3_recall[0]:+.3f}}}",
        rf"\newcommand{{\PrimaryGroupRecallLow}}{{{p3_recall[1]:+.3f}}}",
        rf"\newcommand{{\PrimaryGroupRecallHigh}}{{{p3_recall[2]:+.3f}}}",
        rf"\newcommand{{\PrimaryOvercorrection}}{{{p3_over[0]:+.3f}}}",
        rf"\newcommand{{\PrimaryOvercorrectionLow}}{{{p3_over[1]:+.3f}}}",
        rf"\newcommand{{\PrimaryOvercorrectionHigh}}{{{p3_over[2]:+.3f}}}",
    ]
    path = GENERATED / "result_macros.tex"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_tables(main: list[dict[str, str]], gov: list[dict[str, str]], natural: list[dict[str, str]], policies: list[dict[str, str]]) -> list[Path]:
    paths: list[Path] = []

    profile_lines = [
        r"\begin{table*}[t]",
        r"\caption{Measurement profiles for the frozen mechanism registry. Harm is permissive-minus-strict test AUROC. D is normalized average precision for the primary mutual-information ranker. Harm intervals are task-hierarchical 95\% intervals. Mechanism rows are descriptive; the prespecified simple-minus-structured contrast is reported in the text.}",
        r"\label{tab:measurement}",
        r"\centering\small",
        r"\begin{tabular}{lllrrr}",
        r"\toprule",
        r"ID & Mechanism & Family & Harm & 95\% CI & D \\",
        r"\midrule",
    ]
    for row in main:
        if row["row_type"] != "mechanism_profile":
            continue
        profile_lines.append(
            f"{row['result_id']} & {tex_escape(row['label'])} & {row['category']} & "
            f"{fmt(row['estimate'], signed=True)} & [{fmt(row['ci_low'], signed=True)}, "
            f"{fmt(row['ci_high'], signed=True)}] & {fmt(row['primary_detectability'])} \\\\" 
        )
    profile_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_measurement.tex"
    path.write_text("\n".join(profile_lines) + "\n", encoding="utf-8")
    paths.append(path)

    gov_lines = [
        r"\begin{table*}[t]",
        r"\caption{Full-B1 policy contrasts under the primary semantic-group 20\% contract. Each entry is the learned policy minus the within-key mean of 20 matched-random P2 seeds, with task-cluster bootstrap 95\% intervals. Positive direction and full-group recall are desirable; positive overcorrection is a cost. The joint gate classifies every policy as a tradeoff.}",
        r"\label{tab:governance}",
        r"\centering\scriptsize",
        r"\begin{tabular}{@{}llcccc@{}}",
        r"\toprule",
        r"Policy & Status & $\Delta$SDR & $\Delta$direction & $\Delta$full recall & $\Delta$overcorr. \\",
        r"\midrule",
    ]
    for row in policies:
        gov_lines.append(
            f"{row['policy']} & {row['claim_status'].title()} & "
            f"{tex_effect(row['delta_legacy_sdr'])} & "
            f"{tex_effect(row['delta_directional_repair'])} & "
            f"{tex_effect(row['delta_full_group_recall'])} & "
            f"{tex_effect(row['delta_overcorrection'])} \\\\"
        )
    gov_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_governance.tex"
    path.write_text("\n".join(gov_lines) + "\n", encoding="utf-8")
    paths.append(path)

    natural_lines = [
        r"\begin{table*}[t]",
        r"\caption{Boundary-specific real-data case studies. These selected tasks provide descriptive consistency checks, not population inference.}",
        r"\label{tab:natural}",
        r"\centering\small",
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"Task & Declared prediction boundary & Features & Leak fields & Mean harm \\",
        r"\midrule",
    ]
    for row in natural:
        natural_lines.append(
            f"{tex_escape(row['task'])} & {tex_escape(row['prediction_boundary'])} & "
            f"{int(float(row['n_features']))} & "
            f"{int(float(row['n_leak_features']))} & {fmt(row['mean_paired_harm'], signed=True)} \\\\"
        )
    natural_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_natural.tex"
    path.write_text("\n".join(natural_lines) + "\n", encoding="utf-8")
    paths.append(path)
    return paths


def save_figure(fig: plt.Figure, stem: str) -> list[Path]:
    pdf_path = FIGURES / f"{stem}.pdf"
    fig.savefig(
        pdf_path,
        bbox_inches="tight",
        metadata={"CreationDate": None, "ModDate": None},
    )
    plt.close(fig)
    return [pdf_path]


def plot_tradeoff(policies: list[dict[str, str]]) -> list[Path]:
    names = [row["policy"] for row in policies]
    metrics = [
        ("delta_directional_repair", "Directional repair", PALETTE["p3"]),
        ("delta_full_group_recall", "Full-group recall", PALETTE["cyan"]),
        ("delta_overcorrection", "Overcorrection", PALETTE["p2"]),
    ]
    y = np.arange(len(names))[::-1]
    fig, axes = plt.subplots(1, 3, figsize=(7.0, 2.25), gridspec_kw={"wspace": 0.42})
    for ax, (field, title, color) in zip(axes, metrics):
        parsed = [parse_interval(row[field]) for row in policies]
        values = np.asarray([item[0] for item in parsed])
        low = np.asarray([item[1] for item in parsed])
        high = np.asarray([item[2] for item in parsed])
        ax.axvline(0, color=PALETTE["neutral"], linewidth=0.8, linestyle="--")
        ax.errorbar(
            values,
            y,
            xerr=np.vstack((values - low, high - values)),
            color=color,
            marker="o",
            markeredgecolor=PALETTE["ink"],
            markeredgewidth=0.5,
            linewidth=1.4,
            capsize=2.3,
        )
        ax.set_yticks(y, names if ax is axes[0] else [])
        ax.set_xlabel("Policy minus P2")
        ax.set_title(title)
    return save_figure(fig, "governance_tradeoff")


def plot_cdx(main: list[dict[str, str]]) -> list[Path]:
    rows = [row for row in main if row["row_type"] == "mechanism_profile"]
    markers = {"simple": "o", "boundary": "D", "structured": "s"}
    fig, ax = plt.subplots(figsize=(3.35, 2.65))
    label_offsets = {
        "M04": (-2, -10),
        "M05": (4, 5),
        "M08": (4, 4),
        "M09": (4, 4),
        "M11": (4, 4),
    }
    for category in ("simple", "boundary", "structured"):
        subset = [row for row in rows if row["category"] == category]
        ax.scatter(
            [number(row["primary_detectability"]) for row in subset],
            [number(row["estimate"]) for row in subset],
            s=30,
            color=PALETTE[category],
            marker=markers[category],
            edgecolor=PALETTE["ink"],
            linewidth=0.5,
            label=category.title(),
            zorder=3,
        )
        for row in subset:
            offset = label_offsets.get(row["result_id"], (3, 3))
            ax.annotate(
                row["result_id"],
                (number(row["primary_detectability"]), number(row["estimate"])),
                xytext=offset,
                textcoords="offset points",
                fontsize=5.7,
            )
    ax.axhline(0, color=PALETTE["neutral"], linewidth=0.7, linestyle="--", zorder=0)
    ax.set_xlim(-0.03, 1.04)
    ax.set_xlabel("Detectability D (normalized AP)")
    ax.set_ylabel("Exploitability X (paired AUROC harm)")
    ax.set_title("Detectability does not determine exploitability")
    ax.legend(loc="lower right")
    return save_figure(fig, "cdx_profiles")


def main() -> int:
    GENERATED.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)
    main_rows = read_rows("main_results.csv")
    gov_rows = read_rows("governance_results.csv")
    natural_rows = read_rows("natural_cases.csv")
    policy_rows = read_path(FULL_B1 / "paper_table_1_policy.csv")

    outputs = [write_macros(main_rows, gov_rows, natural_rows, policy_rows)]
    outputs += write_tables(main_rows, gov_rows, natural_rows, policy_rows)
    outputs += plot_tradeoff(policy_rows)
    outputs += plot_cdx(main_rows)

    source_files = [
        SOURCE / "main_results.csv",
        SOURCE / "governance_results.csv",
        SOURCE / "natural_cases.csv",
        SOURCE / "paper_asset_manifest.json",
        FULL_B1 / "paper_table_1_policy.csv",
        FULL_B1 / "analysis_manifest.json",
        Path(__file__),
    ]
    manifest = {
        "schema_version": 1,
        "status": "EDBT_PAPER_ARTIFACTS_READY",
        "palette": PALETTE,
        "source_sha256": {str(path.relative_to(ROOT)): sha256(path) for path in source_files},
        "output_sha256": {str(path.relative_to(PAPER)): sha256(path) for path in outputs},
    }
    manifest_path = GENERATED / "paper_artifact_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"generated {len(outputs)} paper artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
