#!/usr/bin/env python3
"""Generate CDXR paper macros, three tables, and figures from governed CSVs.

The three CSV files in ``source_data/generated`` are the only paper-facing
numeric inputs. This script formats already-derived estimands; it does not
recompute claim states.
"""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np


PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER / "source_data/generated"
GENERATED = PAPER / "generated"
FIGURES = PAPER / "figures/generated"

# Flat colors sampled from the author-provided ML visualization palette.
PALETTE = {
    "p3": "#3F2B96",
    "p2": "#A8C0FF",
    "simple": "#FE9696",
    "boundary": "#E6B94E",
    "structured": "#B6D7A8",
    "lavender": "#DBD4EB",
    "cyan": "#69D4F4",
    "ink": "#4A4655",
    "neutral": "#8A8793",
    "grid": "#E8E6EC",
}

mpl.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": 7,
        "axes.labelsize": 7,
        "axes.titlesize": 8,
        "xtick.labelsize": 6.5,
        "ytick.labelsize": 6.5,
        "legend.fontsize": 6.5,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.linewidth": 0.7,
        "legend.frameon": False,
        "svg.fonttype": "none",
        "svg.hashsalt": "cdxr-edbt-eab-v2",
        "pdf.fonttype": 42,
    }
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_rows(name: str) -> list[dict[str, str]]:
    with (SOURCE / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def number(value: str) -> float:
    return float(value)


def fmt(value: str | float, digits: int = 3, signed: bool = False) -> str:
    numeric = float(value)
    return f"{numeric:+.{digits}f}" if signed else f"{numeric:.{digits}f}"


def tex_escape(value: str) -> str:
    replacements = {"&": r"\&", "%": r"\%", "_": r"\_", "#": r"\#"}
    return "".join(replacements.get(char, char) for char in value)


def select_one(rows: list[dict[str, str]], **criteria: str) -> dict[str, str]:
    matches = [row for row in rows if all(row[key] == value for key, value in criteria.items())]
    if len(matches) != 1:
        raise ValueError(f"expected one row for {criteria}, found {len(matches)}")
    return matches[0]


def interval(row: dict[str, str]) -> str:
    return f"[{fmt(row['ci_low'], signed=True)}, {fmt(row['ci_high'], signed=True)}]"


def write_macros(
    main: list[dict[str, str]], gov: list[dict[str, str]], natural: list[dict[str, str]]
) -> Path:
    contrast = select_one(main, result_id="C1")
    budget = {
        row["budget_fraction"]: row for row in gov if row["row_type"] == "budget"
    }
    learners = {
        row["learner"]: row for row in gov if row["row_type"] == "learner_overall"
    }
    family = {
        row["scope"]: row
        for row in gov
        if row["row_type"] == "family" and row["learner"] == "LR"
    }
    m09 = select_one(gov, row_type="mechanism", scope="M09", learner="LR")
    sparse = select_one(gov, row_type="archetype", scope="sparse", learner="LR")
    sparse_anatomy = select_one(gov, row_type="failure_anatomy", scope="sparse", learner="LR")
    q4 = select_one(gov, row_type="gap_quartile", scope="Q4_high", learner="LR")
    semantic_overall = select_one(
        gov, row_type="cost_sensitivity", scope="All mechanisms", learner="LR", cost_unit="semantic group"
    )
    semantic_m09 = select_one(
        gov, row_type="cost_sensitivity", scope="M09", learner="LR", cost_unit="semantic group"
    )
    encoded_overall = select_one(
        gov, row_type="cost_sensitivity", scope="All mechanisms", learner="LR", cost_unit="encoded column"
    )
    nyc311 = select_one(natural, task="NYC311")
    lines = [
        "% Generated by source_data/generate_paper_artifacts.py; do not edit.",
        r"\newcommand{\CoreCellCount}{27,500}",
        r"\newcommand{\GovernanceCellCount}{709,500}",
        r"\newcommand{\GovernanceKeyCount}{5,500}",
        rf"\newcommand{{\CoreContrast}}{{{fmt(contrast['estimate'])}}}",
        rf"\newcommand{{\CoreContrastLow}}{{{fmt(contrast['ci_low'])}}}",
        rf"\newcommand{{\CoreContrastHigh}}{{{fmt(contrast['ci_high'])}}}",
        rf"\newcommand{{\CoreContrastP}}{{{float(contrast['holm_p']):.2e}}}",
        rf"\newcommand{{\GovTwentyDiff}}{{{fmt(budget['0.2']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyLow}}{{{fmt(budget['0.2']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyHigh}}{{{fmt(budget['0.2']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyProb}}{{{100 * number(budget['0.2']['probability_positive']):.1f}\%}}",
        rf"\newcommand{{\GovOneDiff}}{{{fmt(budget['0.01']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovOneRecall}}{{{100 * number(budget['0.01']['p3_recall']):.1f}\%}}",
        rf"\newcommand{{\GovOneRetention}}{{{100 * number(budget['0.01']['p3_legitimate_retention']):.1f}\%}}",
        rf"\newcommand{{\GovRFDiff}}{{{fmt(learners['RF']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovRFLow}}{{{fmt(learners['RF']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovRFHigh}}{{{fmt(learners['RF']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovLGBMDiff}}{{{fmt(learners['LightGBM']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovLGBMLow}}{{{fmt(learners['LightGBM']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovLGBMHigh}}{{{fmt(learners['LightGBM']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleDiff}}{{{fmt(family['simple']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleLow}}{{{fmt(family['simple']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleHigh}}{{{fmt(family['simple']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryDiff}}{{{fmt(family['boundary']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryLow}}{{{fmt(family['boundary']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryHigh}}{{{fmt(family['boundary']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredDiff}}{{{fmt(family['structured']['effect'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredLow}}{{{fmt(family['structured']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredHigh}}{{{fmt(family['structured']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovMNineDiff}}{{{fmt(m09['effect'], signed=True)}}}",
        rf"\newcommand{{\GovMNineLow}}{{{fmt(m09['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovMNineHigh}}{{{fmt(m09['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovSparseDiff}}{{{fmt(sparse['effect'], signed=True)}}}",
        rf"\newcommand{{\GovSparseLow}}{{{fmt(sparse['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovSparseHigh}}{{{fmt(sparse['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovSparseNegativeTasks}}{{{int(number(sparse_anatomy['negative_task_count']))}/4}}",
        rf"\newcommand{{\GovSparseNegativeMechanisms}}{{{int(number(sparse_anatomy['negative_mechanism_count']))}/11}}",
        rf"\newcommand{{\GovSparseRecall}}{{{100 * number(sparse_anatomy['p3_recall']):.1f}\%}}",
        rf"\newcommand{{\GovSparseRetention}}{{{100 * number(sparse_anatomy['p3_legitimate_retention']):.1f}\%}}",
        rf"\newcommand{{\GovSparseSignalRemoved}}{{{number(sparse_anatomy['mean_signal_fields_removed']):.2f}}}",
        rf"\newcommand{{\GovSparseXZeroRemoval}}{{{100 * number(sparse_anatomy['signal_x000_removal_rate']):.1f}\%}}",
        rf"\newcommand{{\GovSparseXThreeRemoval}}{{{100 * number(sparse_anatomy['signal_x003_removal_rate']):.1f}\%}}",
        rf"\newcommand{{\GovSparseXFiveRemoval}}{{{100 * number(sparse_anatomy['signal_x005_removal_rate']):.1f}\%}}",
        rf"\newcommand{{\GovQFourDiff}}{{{fmt(q4['effect'], signed=True)}}}",
        rf"\newcommand{{\GovQFourLow}}{{{fmt(q4['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovQFourHigh}}{{{fmt(q4['ci_high'], signed=True)}}}",
        rf"\newcommand{{\EncodedOverallDiff}}{{{fmt(encoded_overall['effect'], signed=True)}}}",
        rf"\newcommand{{\SemanticOverallDiff}}{{{fmt(semantic_overall['effect'], signed=True)}}}",
        rf"\newcommand{{\SemanticOverallLow}}{{{fmt(semantic_overall['ci_low'], signed=True)}}}",
        rf"\newcommand{{\SemanticOverallHigh}}{{{fmt(semantic_overall['ci_high'], signed=True)}}}",
        rf"\newcommand{{\SemanticMNineDiff}}{{{fmt(semantic_m09['effect'], signed=True)}}}",
        rf"\newcommand{{\SemanticMNineLow}}{{{fmt(semantic_m09['ci_low'], signed=True)}}}",
        rf"\newcommand{{\SemanticMNineHigh}}{{{fmt(semantic_m09['ci_high'], signed=True)}}}",
        rf"\newcommand{{\NaturalCaseCount}}{{{len(natural)}}}",
        rf"\newcommand{{\NaturalMeanHarm}}{{{fmt(np.mean([number(row['mean_paired_harm']) for row in natural]))}}}",
        rf"\newcommand{{\NaturalMeanRepair}}{{{fmt(np.mean([number(row['governance_effect']) for row in natural]), signed=True)}}}",
        rf"\newcommand{{\NYCInitialGap}}{{{fmt(nyc311['initial_gap'])}}}",
        rf"\newcommand{{\NYCRepairDiff}}{{{fmt(nyc311['governance_effect'], signed=True)}}}",
        rf"\newcommand{{\NYCRecall}}{{{100 * number(nyc311['p3_leak_recall']):.1f}\%}}",
        rf"\newcommand{{\NYCRetention}}{{{100 * number(nyc311['p3_legitimate_retention']):.1f}\%}}",
        rf"\newcommand{{\NYCRemovedInvalid}}{{{int(number(nyc311['p3_removed_invalid_count']))}}}",
        rf"\newcommand{{\NYCRemovedValid}}{{{int(number(nyc311['p3_removed_valid_count']))}}}",
    ]
    path = GENERATED / "result_macros.tex"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_tables(
    main: list[dict[str, str]], gov: list[dict[str, str]], natural: list[dict[str, str]]
) -> list[Path]:
    paths: list[Path] = []

    profile_lines = [
        r"\begin{table*}[t]",
        r"\caption{CDX measurement profiles for the frozen mechanism registry. X is permissive-minus-strict test AUROC; D is normalized average precision for the primary training-side MI ranker. Intervals are 95\% task-hierarchical intervals. Mechanism rows are descriptive; the prespecified simple-minus-structured contrast appears in the text.}",
        r"\label{tab:measurement}",
        r"\centering\small",
        r"\begin{tabular}{lllrrr}",
        r"\toprule",
        r"ID & Mechanism & Family & X & 95\% interval & D \\",
        r"\midrule",
    ]
    for row in main:
        if row["row_type"] != "mechanism_profile":
            continue
        profile_lines.append(
            f"{row['result_id']} & {tex_escape(row['label'])} & {row['category']} & "
            f"{fmt(row['estimate'], signed=True)} & [{fmt(row['ci_low'], signed=True)}, "
            f"{fmt(row['ci_high'], signed=True)}] & {fmt(row['primary_detectability'])} \\\\"
        )
    profile_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_measurement.tex"
    path.write_text("\n".join(profile_lines) + "\n", encoding="utf-8")
    paths.append(path)

    selected = [
        ("Across learners", select_one(gov, row_type="learner_overall", learner="LR")),
        ("Across learners", select_one(gov, row_type="learner_overall", learner="RF")),
        ("Across learners", select_one(gov, row_type="learner_overall", learner="LightGBM")),
        ("Mechanism family", select_one(gov, row_type="family", scope="simple", learner="LR")),
        ("Mechanism family", select_one(gov, row_type="family", scope="boundary", learner="LR")),
        ("Mechanism family", select_one(gov, row_type="family", scope="structured", learner="LR")),
        ("Counterexample", select_one(gov, row_type="mechanism", scope="M09", learner="LR")),
        ("Opportunity", select_one(gov, row_type="gap_quartile", scope="Q1_low", learner="LR")),
        ("Opportunity", select_one(gov, row_type="gap_quartile", scope="Q4_high", learner="LR")),
        ("Archetype", select_one(gov, row_type="archetype", scope="sparse", learner="LR")),
    ]
    gov_lines = [
        r"\begin{table*}[t]",
        r"\caption{CDXR repair stress tests at the 20\% encoded-column budget. $\Delta_R$ is P3 minus the within-key mean of 20 matched P2 realizations; positive values favor blind MI. Intervals resample the 20 controlled tasks, except archetype rows, which contain four tasks. Opportunity strata are sensitivity analyses, not causal effects.}",
        r"\label{tab:governance}",
        r"\centering\small",
        r"\begin{tabular}{lllrrrl}",
        r"\toprule",
        r"Stress test & Scope & Learner & Opportunity & $\Delta_R$ & 95\% interval & Unit \\",
        r"\midrule",
    ]
    for stress, row in selected:
        opportunity = "--"
        if row["row_type"] == "mechanism":
            opportunity = fmt(row["initial_gap"])
        elif row["row_type"] == "gap_quartile":
            opportunity = tex_escape(row["gap_range"])
        unit = f"{int(float(row['n_keys']))} keys" if row["n_keys"] else f"{int(float(row['n_tasks']))} tasks"
        gov_lines.append(
            f"{stress} & {tex_escape(row['scope'])} & {row['learner']} & {opportunity} & "
            f"{fmt(row['effect'], signed=True)} & {interval(row)} & {unit} \\\\"
        )
    gov_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_governance.tex"
    path.write_text("\n".join(gov_lines) + "\n", encoding="utf-8")
    paths.append(path)

    cost_rows = [
        select_one(gov, row_type="cost_sensitivity", scope="All mechanisms", cost_unit="encoded column"),
        select_one(gov, row_type="cost_sensitivity", scope="All mechanisms", cost_unit="semantic group"),
        select_one(gov, row_type="cost_sensitivity", scope="M09", cost_unit="semantic group"),
    ]
    natural_lines = [
        r"\begin{table*}[t]",
        r"\caption{Context and cost-contract sensitivities. Natural rows report fixed-case harm (X) and LR repair response at 20\%; no case-level inferential interval is claimed. Cost rows report controlled-registry $\Delta_R$ with 95\% task-cluster intervals. Natural governance is mixed because NYC311 is negative.}",
        r"\label{tab:natural}",
        r"\centering\small",
        r"\begin{tabular}{lllrrrl}",
        r"\toprule",
        r"Setting & Case / scope & Boundary or cost & X / opportunity & $\Delta_R$ & 95\% interval & Evidence \\",
        r"\midrule",
    ]
    for row in natural:
        natural_lines.append(
            f"Natural & {tex_escape(row['task'])} & {tex_escape(row['prediction_boundary'])} & "
            f"{fmt(row['mean_paired_harm'], signed=True)} & {fmt(row['governance_effect'], signed=True)} & -- & fixed case \\\\"
        )
    natural_lines.append(r"\midrule")
    for row in cost_rows:
        evidence = "interval crosses 0" if float(row["ci_low"]) <= 0 <= float(row["ci_high"]) else "positive interval"
        natural_lines.append(
            f"Cost & {tex_escape(row['scope'])} & {tex_escape(row['cost_unit'])} & -- & "
            f"{fmt(row['effect'], signed=True)} & {interval(row)} & {evidence} \\\\"
        )
    natural_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_natural.tex"
    path.write_text("\n".join(natural_lines) + "\n", encoding="utf-8")
    paths.append(path)
    return paths


def save_figure(fig: plt.Figure, stem: str) -> list[Path]:
    svg_path = FIGURES / f"{stem}.svg"
    pdf_path = FIGURES / f"{stem}.pdf"
    png_path = FIGURES / f"{stem}.png"
    tiff_path = FIGURES / f"{stem}.tiff"
    fig.savefig(svg_path, bbox_inches="tight", metadata={"Date": None})
    # Matplotlib emits trailing spaces in SVG path data. Normalize them so the
    # generated artifacts pass repository whitespace checks byte-for-byte.
    svg_text = svg_path.read_text(encoding="utf-8")
    svg_path.write_text(
        "\n".join(line.rstrip() for line in svg_text.splitlines()) + "\n",
        encoding="utf-8",
    )
    fig.savefig(pdf_path, bbox_inches="tight", metadata={"CreationDate": None, "ModDate": None})
    fig.savefig(png_path, dpi=300, bbox_inches="tight")
    fig.savefig(tiff_path, dpi=600, bbox_inches="tight")
    plt.close(fig)
    return [svg_path, pdf_path, png_path, tiff_path]


def plot_budget(gov: list[dict[str, str]]) -> list[Path]:
    rows = sorted(
        (row for row in gov if row["row_type"] == "budget"),
        key=lambda row: number(row["budget_fraction"]),
    )
    x = np.asarray([100 * number(row["budget_fraction"]) for row in rows])
    diff = np.asarray([number(row["effect"]) for row in rows])
    low = np.asarray([number(row["ci_low"]) for row in rows])
    high = np.asarray([number(row["ci_high"]) for row in rows])
    recall = np.asarray([100 * number(row["p3_recall"]) for row in rows])
    retention = np.asarray([100 * number(row["p3_legitimate_retention"]) for row in rows])

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.45), gridspec_kw={"wspace": 0.32})
    ax = axes[0]
    ax.axhline(0, color=PALETTE["neutral"], linewidth=0.8, linestyle="--", zorder=0)
    ax.errorbar(
        x, diff, yerr=np.vstack((diff - low, high - diff)), color=PALETTE["p3"],
        marker="o", markersize=4.2, linewidth=1.5, capsize=2.5,
    )
    ax.set_xticks(x, [f"{value:g}%" for value in x])
    ax.set_xlabel("Nominal encoded-column budget")
    ax.set_ylabel(r"Repair advantage $\Delta_R$")
    ax.set_title("a  MI adds value beyond equal-count deletion")

    ax = axes[1]
    ax.plot(x, recall, color=PALETTE["p3"], marker="o", linewidth=1.5, label="Leak recall")
    ax.plot(
        x, retention, color=PALETTE["p2"], marker="s", markeredgecolor=PALETTE["ink"],
        markeredgewidth=0.5, linewidth=1.5, linestyle="--", label="Legitimate retention",
    )
    ax.set_xticks(x, [f"{value:g}%" for value in x])
    ax.set_ylim(0, 102)
    ax.set_xlabel("Nominal encoded-column budget")
    ax.set_ylabel("P3 localization outcome (%)")
    ax.set_title("b  Repair trades recall against retention")
    ax.legend(loc="lower left")
    return save_figure(fig, "governance_budget")


def plot_categories(gov: list[dict[str, str]]) -> list[Path]:
    order = ["simple", "boundary", "structured"]
    rows = {
        row["scope"]: row
        for row in gov
        if row["row_type"] == "family" and row["learner"] == "LR"
    }
    values = np.asarray([number(rows[name]["effect"]) for name in order])
    low = np.asarray([number(rows[name]["ci_low"]) for name in order])
    high = np.asarray([number(rows[name]["ci_high"]) for name in order])
    y = np.arange(len(order))[::-1]

    fig, ax = plt.subplots(figsize=(3.35, 2.25))
    ax.axvline(0, color=PALETTE["neutral"], linewidth=0.8, linestyle="--", zorder=0)
    for index, name in enumerate(order):
        ax.errorbar(
            values[index], y[index],
            xerr=[[values[index] - low[index]], [high[index] - values[index]]],
            color=PALETTE[name], marker=["o", "D", "s"][index],
            markeredgecolor=PALETTE["ink"], markeredgewidth=0.6,
            markersize=5, linewidth=1.6, capsize=2.5,
        )
    ax.set_yticks(y, [name.title() for name in order])
    ax.set_xlabel(r"Repair advantage $\Delta_R$ at 20%")
    ax.set_title("Repair response is mechanism-dependent")
    return save_figure(fig, "governance_by_category")


def plot_cdx(main: list[dict[str, str]]) -> list[Path]:
    rows = [row for row in main if row["row_type"] == "mechanism_profile"]
    markers = {"simple": "o", "boundary": "D", "structured": "s"}
    fig, ax = plt.subplots(figsize=(3.35, 2.65))
    label_offsets = {"M04": (-2, -10), "M05": (4, 5), "M08": (4, 4), "M09": (4, 4), "M11": (4, 4)}
    for category in ("simple", "boundary", "structured"):
        subset = [row for row in rows if row["category"] == category]
        ax.scatter(
            [number(row["primary_detectability"]) for row in subset],
            [number(row["estimate"]) for row in subset],
            s=30, color=PALETTE[category], marker=markers[category],
            edgecolor=PALETTE["ink"], linewidth=0.5, label=category.title(), zorder=3,
        )
        for row in subset:
            ax.annotate(
                row["result_id"],
                (number(row["primary_detectability"]), number(row["estimate"])),
                xytext=label_offsets.get(row["result_id"], (3, 3)),
                textcoords="offset points", fontsize=5.7,
            )
    ax.axhline(0, color=PALETTE["neutral"], linewidth=0.7, linestyle="--", zorder=0)
    ax.set_xlim(-0.03, 1.04)
    ax.set_xlabel("Detectability D (normalized AP)")
    ax.set_ylabel("Exploitability X (paired AUROC harm)")
    ax.set_title("Detectability does not determine exploitability")
    ax.legend(loc="lower right")
    return save_figure(fig, "cdx_profiles")


def main() -> int:
    GENERATED.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)
    main_rows = read_rows("main_results.csv")
    gov_rows = read_rows("governance_results.csv")
    natural_rows = read_rows("natural_cases.csv")

    outputs = [write_macros(main_rows, gov_rows, natural_rows)]
    outputs += write_tables(main_rows, gov_rows, natural_rows)
    outputs += plot_budget(gov_rows)
    outputs += plot_categories(gov_rows)
    outputs += plot_cdx(main_rows)

    source_files = [
        SOURCE / "main_results.csv",
        SOURCE / "governance_results.csv",
        SOURCE / "natural_cases.csv",
        SOURCE / "paper_asset_manifest.json",
        Path(__file__),
    ]
    manifest = {
        "schema_version": 2,
        "status": "CDXR_PAPER_ARTIFACTS_READY",
        "palette": PALETTE,
        "source_sha256": {str(path.relative_to(PAPER)): sha256(path) for path in source_files},
        "output_sha256": {str(path.relative_to(PAPER)): sha256(path) for path in outputs},
    }
    manifest_path = GENERATED / "paper_artifact_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"generated {len(outputs)} paper artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
