#!/usr/bin/env python3
"""Generate EDBT paper macros, tables, and figures from governed CSV assets.

The three CSV files in ``source_data/generated`` are the only paper-facing
numeric inputs.  This script performs formatting and visualization only; it
does not recompute estimands or claim states.
"""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np


PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER / "source_data/generated"
GENERATED = PAPER / "generated"
FIGURES = PAPER / "figures/generated"

# Flat colors sampled from the author-provided ML visualization palette.
PALETTE = {
    "p3": "#3F2B96",
    "p2": "#A8C0FF",
    "simple": "#FE9696",
    "boundary": "#E6B94E",
    "structured": "#B6D7A8",
    "lavender": "#DBD4EB",
    "cyan": "#69D4F4",
    "ink": "#4A4655",
    "neutral": "#8A8793",
    "grid": "#E8E6EC",
}

mpl.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": 7,
        "axes.labelsize": 7,
        "axes.titlesize": 8,
        "xtick.labelsize": 6.5,
        "ytick.labelsize": 6.5,
        "legend.fontsize": 6.5,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.linewidth": 0.7,
        "legend.frameon": False,
        "svg.fonttype": "none",
        "svg.hashsalt": "leakbench-edbt-eab-v1",
        "pdf.fonttype": 42,
    }
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_rows(name: str) -> list[dict[str, str]]:
    with (SOURCE / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def number(value: str) -> float:
    return float(value)


def fmt(value: str | float, digits: int = 3, signed: bool = False) -> str:
    numeric = float(value)
    return f"{numeric:+.{digits}f}" if signed else f"{numeric:.{digits}f}"


def tex_escape(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "_": r"\_",
        "#": r"\#",
    }
    return "".join(replacements.get(char, char) for char in value)


def write_macros(main: list[dict[str, str]], gov: list[dict[str, str]], natural: list[dict[str, str]]) -> Path:
    contrast = next(row for row in main if row["result_id"] == "C1")
    budget = {row["scope"]: row for row in gov if row["row_type"] == "budget"}
    category = {row["scope"]: row for row in gov if row["row_type"] == "category_at_20pct"}
    lines = [
        "% Generated by source_data/generate_paper_artifacts.py; do not edit.",
        rf"\newcommand{{\CoreCellCount}}{{27,500}}",
        rf"\newcommand{{\GovernanceCellCount}}{{55,000}}",
        rf"\newcommand{{\GovernanceKeyCount}}{{5,500}}",
        rf"\newcommand{{\CoreContrast}}{{{fmt(contrast['estimate'])}}}",
        rf"\newcommand{{\CoreContrastLow}}{{{fmt(contrast['ci_low'])}}}",
        rf"\newcommand{{\CoreContrastHigh}}{{{fmt(contrast['ci_high'])}}}",
        rf"\newcommand{{\CoreContrastP}}{{{float(contrast['holm_p']):.2e}}}",
        rf"\newcommand{{\GovTwentyDiff}}{{{fmt(budget['20% budget']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyLow}}{{{fmt(budget['20% budget']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyHigh}}{{{fmt(budget['20% budget']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovTwentyProb}}{{{100 * number(budget['20% budget']['p3_better_probability']):.1f}\%}}",
        rf"\newcommand{{\GovOneDiff}}{{{fmt(budget['1% budget']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovOneRecall}}{{{100 * number(budget['1% budget']['p3_recall']):.1f}\%}}",
        rf"\newcommand{{\GovOneRetention}}{{{100 * number(budget['1% budget']['p3_legitimate_retention']):.1f}\%}}",
        rf"\newcommand{{\GovSimpleDiff}}{{{fmt(category['simple']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleLow}}{{{fmt(category['simple']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovSimpleHigh}}{{{fmt(category['simple']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryDiff}}{{{fmt(category['boundary']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryLow}}{{{fmt(category['boundary']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovBoundaryHigh}}{{{fmt(category['boundary']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredDiff}}{{{fmt(category['structured']['p3_minus_p2_sdr'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredLow}}{{{fmt(category['structured']['ci_low'], signed=True)}}}",
        rf"\newcommand{{\GovStructuredHigh}}{{{fmt(category['structured']['ci_high'], signed=True)}}}",
        rf"\newcommand{{\NaturalCaseCount}}{{{len(natural)}}}",
        rf"\newcommand{{\NaturalMeanHarm}}{{{fmt(np.mean([number(row['mean_paired_harm']) for row in natural]))}}}",
    ]
    path = GENERATED / "result_macros.tex"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_tables(main: list[dict[str, str]], gov: list[dict[str, str]], natural: list[dict[str, str]]) -> list[Path]:
    paths: list[Path] = []

    profile_lines = [
        r"\begin{table*}[t]",
        r"\caption{Measurement profiles for the frozen mechanism registry. Harm is permissive-minus-strict test AUROC. D is normalized average precision for the primary mutual-information ranker. Harm intervals are task-hierarchical 95\% intervals. Mechanism rows are descriptive; the prespecified simple-minus-structured contrast is reported in the text.}",
        r"\label{tab:measurement}",
        r"\centering\small",
        r"\begin{tabular}{lllrrr}",
        r"\toprule",
        r"ID & Mechanism & Family & Harm & 95\% CI & D \\",
        r"\midrule",
    ]
    for row in main:
        if row["row_type"] != "mechanism_profile":
            continue
        profile_lines.append(
            f"{row['result_id']} & {tex_escape(row['label'])} & {row['category']} & "
            f"{fmt(row['estimate'], signed=True)} & [{fmt(row['ci_low'], signed=True)}, "
            f"{fmt(row['ci_high'], signed=True)}] & {fmt(row['primary_detectability'])} \\\\" 
        )
    profile_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_measurement.tex"
    path.write_text("\n".join(profile_lines) + "\n", encoding="utf-8")
    paths.append(path)

    gov_lines = [
        r"\begin{table*}[t]",
        r"\caption{Matched-cost governance results. Differences are P3 minus P2 strict-distance reduction (SDR); positive values favor blind MI. Probability is the fraction of paired dataset-cluster bootstrap draws above zero, not a $p$-value. Recall and retention describe P3.}",
        r"\label{tab:governance}",
        r"\centering\small",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Scope & Budget & P3--P2 SDR & 95\% CI & $\Pr_{boot}(\Delta>0)$ & Leak recall & Legit. retention \\",
        r"\midrule",
    ]
    for row in gov:
        scope = row["scope"] if row["row_type"] == "category_at_20pct" else "All mechanisms"
        budget_label = (
            r"20\%"
            if row["row_type"] == "category_at_20pct"
            else row["scope"].replace(" budget", "").replace("%", r"\%")
        )
        gov_lines.append(
            f"{scope.title()} & {budget_label} & {fmt(row['p3_minus_p2_sdr'], signed=True)} & "
            f"[{fmt(row['ci_low'], signed=True)}, {fmt(row['ci_high'], signed=True)}] & "
            f"{number(row['p3_better_probability']):.3f} & "
            f"{100 * number(row['p3_recall']):.1f}\\% & "
            f"{100 * number(row['p3_legitimate_retention']):.1f}\\% \\\\"
        )
    gov_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_governance.tex"
    path.write_text("\n".join(gov_lines) + "\n", encoding="utf-8")
    paths.append(path)

    natural_lines = [
        r"\begin{table*}[t]",
        r"\caption{Boundary-specific real-data case studies. These selected tasks provide descriptive consistency checks, not population inference.}",
        r"\label{tab:natural}",
        r"\centering\small",
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"Task & Declared prediction boundary & Features & Leak fields & Mean harm \\",
        r"\midrule",
    ]
    for row in natural:
        natural_lines.append(
            f"{tex_escape(row['task'])} & {tex_escape(row['prediction_boundary'])} & "
            f"{int(float(row['n_features']))} & "
            f"{int(float(row['n_leak_features']))} & {fmt(row['mean_paired_harm'], signed=True)} \\\\"
        )
    natural_lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    path = GENERATED / "table_natural.tex"
    path.write_text("\n".join(natural_lines) + "\n", encoding="utf-8")
    paths.append(path)
    return paths


def save_figure(fig: plt.Figure, stem: str) -> list[Path]:
    svg_path = FIGURES / f"{stem}.svg"
    pdf_path = FIGURES / f"{stem}.pdf"
    png_path = FIGURES / f"{stem}.png"
    tiff_path = FIGURES / f"{stem}.tiff"
    fig.savefig(svg_path, bbox_inches="tight", metadata={"Date": None})
    fig.savefig(
        pdf_path,
        bbox_inches="tight",
        metadata={"CreationDate": None, "ModDate": None},
    )
    fig.savefig(png_path, dpi=300, bbox_inches="tight")
    fig.savefig(tiff_path, dpi=600, bbox_inches="tight")
    plt.close(fig)
    return [svg_path, pdf_path, png_path, tiff_path]


def plot_budget(gov: list[dict[str, str]]) -> list[Path]:
    rows = sorted(
        (row for row in gov if row["row_type"] == "budget"),
        key=lambda row: number(row["budget_fraction"]),
    )
    x = np.asarray([100 * number(row["budget_fraction"]) for row in rows])
    diff = np.asarray([number(row["p3_minus_p2_sdr"]) for row in rows])
    low = np.asarray([number(row["ci_low"]) for row in rows])
    high = np.asarray([number(row["ci_high"]) for row in rows])
    recall = np.asarray([100 * number(row["p3_recall"]) for row in rows])
    retention = np.asarray([100 * number(row["p3_legitimate_retention"]) for row in rows])

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.45), gridspec_kw={"wspace": 0.32})
    ax = axes[0]
    ax.axhline(0, color=PALETTE["neutral"], linewidth=0.8, linestyle="--", zorder=0)
    ax.errorbar(
        x,
        diff,
        yerr=np.vstack((diff - low, high - diff)),
        color=PALETTE["p3"],
        marker="o",
        markersize=4.2,
        linewidth=1.5,
        capsize=2.5,
    )
    ax.set_xticks(x, [f"{value:g}%" for value in x])
    ax.set_xlabel("Nominal removal budget")
    ax.set_ylabel("P3 minus P2 SDR")
    ax.set_title("a  Blind MI outperforms random removal")

    ax = axes[1]
    ax.plot(x, recall, color=PALETTE["p3"], marker="o", linewidth=1.5, label="Leak recall")
    ax.plot(
        x,
        retention,
        color=PALETTE["p2"],
        marker="s",
        markeredgecolor=PALETTE["ink"],
        markeredgewidth=0.5,
        linewidth=1.5,
        linestyle="--",
        label="Legitimate retention",
    )
    ax.set_xticks(x, [f"{value:g}%" for value in x])
    ax.set_ylim(0, 102)
    ax.set_xlabel("Nominal removal budget")
    ax.set_ylabel("P3 outcome (%)")
    ax.set_title("b  Small budgets preserve legitimate fields")
    ax.legend(loc="lower left")
    return save_figure(fig, "governance_budget")


def plot_categories(gov: list[dict[str, str]]) -> list[Path]:
    order = ["simple", "boundary", "structured"]
    rows = {row["scope"]: row for row in gov if row["row_type"] == "category_at_20pct"}
    values = np.asarray([number(rows[name]["p3_minus_p2_sdr"]) for name in order])
    low = np.asarray([number(rows[name]["ci_low"]) for name in order])
    high = np.asarray([number(rows[name]["ci_high"]) for name in order])
    y = np.arange(len(order))[::-1]

    fig, ax = plt.subplots(figsize=(3.35, 2.25))
    ax.axvline(0, color=PALETTE["neutral"], linewidth=0.8, linestyle="--", zorder=0)
    for index, name in enumerate(order):
        ax.errorbar(
            values[index],
            y[index],
            xerr=[[values[index] - low[index]], [high[index] - values[index]]],
            color=PALETTE[name],
            marker=["o", "D", "s"][index],
            markeredgecolor=PALETTE["ink"],
            markeredgewidth=0.6,
            markersize=5,
            linewidth=1.6,
            capsize=2.5,
        )
    ax.set_yticks(y, [name.title() for name in order])
    ax.set_xlabel("P3 minus P2 SDR at 20% budget")
    ax.set_title("Governance advantage is mechanism-dependent")
    return save_figure(fig, "governance_by_category")


def plot_cdx(main: list[dict[str, str]]) -> list[Path]:
    rows = [row for row in main if row["row_type"] == "mechanism_profile"]
    markers = {"simple": "o", "boundary": "D", "structured": "s"}
    fig, ax = plt.subplots(figsize=(3.35, 2.65))
    label_offsets = {
        "M04": (-2, -10),
        "M05": (4, 5),
        "M08": (4, 4),
        "M09": (4, 4),
        "M11": (4, 4),
    }
    for category in ("simple", "boundary", "structured"):
        subset = [row for row in rows if row["category"] == category]
        ax.scatter(
            [number(row["primary_detectability"]) for row in subset],
            [number(row["estimate"]) for row in subset],
            s=30,
            color=PALETTE[category],
            marker=markers[category],
            edgecolor=PALETTE["ink"],
            linewidth=0.5,
            label=category.title(),
            zorder=3,
        )
        for row in subset:
            offset = label_offsets.get(row["result_id"], (3, 3))
            ax.annotate(
                row["result_id"],
                (number(row["primary_detectability"]), number(row["estimate"])),
                xytext=offset,
                textcoords="offset points",
                fontsize=5.7,
            )
    ax.axhline(0, color=PALETTE["neutral"], linewidth=0.7, linestyle="--", zorder=0)
    ax.set_xlim(-0.03, 1.04)
    ax.set_xlabel("Detectability D (normalized AP)")
    ax.set_ylabel("Exploitability X (paired AUROC harm)")
    ax.set_title("Detectability does not determine exploitability")
    ax.legend(loc="lower right")
    return save_figure(fig, "cdx_profiles")


def main() -> int:
    GENERATED.mkdir(parents=True, exist_ok=True)
    FIGURES.mkdir(parents=True, exist_ok=True)
    main_rows = read_rows("main_results.csv")
    gov_rows = read_rows("governance_results.csv")
    natural_rows = read_rows("natural_cases.csv")

    outputs = [write_macros(main_rows, gov_rows, natural_rows)]
    outputs += write_tables(main_rows, gov_rows, natural_rows)
    outputs += plot_budget(gov_rows)
    outputs += plot_categories(gov_rows)
    outputs += plot_cdx(main_rows)

    source_files = [
        SOURCE / "main_results.csv",
        SOURCE / "governance_results.csv",
        SOURCE / "natural_cases.csv",
        SOURCE / "paper_asset_manifest.json",
        Path(__file__),
    ]
    manifest = {
        "schema_version": 1,
        "status": "EDBT_PAPER_ARTIFACTS_READY",
        "palette": PALETTE,
        "source_sha256": {str(path.relative_to(PAPER)): sha256(path) for path in source_files},
        "output_sha256": {str(path.relative_to(PAPER)): sha256(path) for path in outputs},
    }
    manifest_path = GENERATED / "paper_artifact_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"generated {len(outputs)} paper artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
